### ISSUE TITLE
Error messages on first export

### ISSUE THREAD

**Issue by kinsidar** [peterennis/aegit#16]
I've successfully exported my database, but few error messages come up in the process:

![capture048](https://user-images.githubusercontent.com/13373809/31694923-f336cba8-b35b-11e7-8d12-6331bd4dd45c.png)

![capture049](https://user-images.githubusercontent.com/13373809/31694924-f686bbc4-b35b-11e7-8592-1dba1556aebe.png)

![capture050](https://user-images.githubusercontent.com/13373809/31694926-f8c9c89a-b35b-11e7-87ff-ddcd9c4b1373.png)

![capture051](https://user-images.githubusercontent.com/13373809/31694929-fb32c424-b35b-11e7-8582-6152c05fcd81.png)

**Comment by peterennis** [comment]
Where is the example? I will fork your repo and see if I can reproduce the error.

**Comment by kinsidar** [comment]
This is the repo of my database: https://github.com/kinsidar/Association-Contacts
Thanks

**Comment by peterennis** [comment]
It seems to be working now. I could not repeat the exact error. Let me know if you can create a
minimum test case.
