### ISSUE TITLE
no tables relationship exported.

### ISSUE THREAD

**Issue by jzhu22** [peterennis/aegit#2]
no tables relationship exported.

**Comment by jzhu22** [comment]
Missing indexes for linked tables. is it a bug in Application.ExportXML? As it works well with other normal tables in the same db. And I tried "OtherFlags" parameter in Application.ExportXML, but failed.

**Comment by peterennisrda** [comment]
A workaround is to add the aegit modules to the data db and run the export from there. The script setup for export would target different folders e.g.
\srcdata
\srcdata\xml
The data db (or other linked data source e.g. SQL Server) will have its own properties and configurations for tracking that are separate for the application front end.
